title: David Hainzl
description: It's-a me
author: David Hainzl
logo: /static/img/avatar.png
github: https://github.com/dhainzl
about: about me ...

baseurl: "https://dhainzl.github.io"
url: "https://dhainzl.github.io"

#disqus_shortname: aboutashu
#google_analytics: UA-72862926-1

share:
  twitter_username: dhainzl
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
