title: David Hainzl
description: Frontend Web Developer // Angular / jQuery / Vanilla JS
author: David Hainzl
logo: https://www.gravatar.com/avatar/ac93032c2c827303713bae179963cf76?s=56
github: https://github.com/dhainzl
about: Frontend Web Dev
baseurl: ""
url: "https://dhainzl.at"
#url: "http://localhost:4000"

sass:
  sass_dir: static/css
  style: compressed

disqus_shortname: dhainzl
google_analytics: UA-86533841-1

share:
  twitter_username: dhainzl
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
